
CREATE DATABASE IF NOT EXISTS littlelemon;
USE littlelemon;

CREATE TABLE IF NOT EXISTS Customer (
    CustomerID INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(100),
    Phone VARCHAR(15),
    Email VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Bookings (
    BookingID INT AUTO_INCREMENT PRIMARY KEY,
    BookingDate DATE,
    TableNo INT,
    CustomerID INT,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);

CREATE TABLE IF NOT EXISTS Menu (
    MenuID INT AUTO_INCREMENT PRIMARY KEY,
    MenuName VARCHAR(100),
    Cuisine VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS MenuItems (
    ItemID INT AUTO_INCREMENT PRIMARY KEY,
    ItemName VARCHAR(100),
    MenuID INT,
    Price DECIMAL(10,2),
    FOREIGN KEY (MenuID) REFERENCES Menu(MenuID)
);

CREATE TABLE IF NOT EXISTS Orders (
    OrderID INT AUTO_INCREMENT PRIMARY KEY,
    OrderDate DATE,
    Quantity INT,
    CustomerID INT,
    ItemID INT,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
    FOREIGN KEY (ItemID) REFERENCES MenuItems(ItemID)
);
